# -*- coding: utf-8 -*-
"""4way plot lol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1huRa16g-350jcNV9kyr7cGuHT6_yMRKt
"""

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

data = pd.read_csv('Final April 2020 SNAP-FI.csv')
data

#data = pd.read_csv('4way data.csv')
xdata = pd.DataFrame({
    'Food insecure individuals (1000)':[31015, 33231, 33642, 34902, 35128, 35207, 35515, 36147, 36229, 36255, 37227, 38196, 40044 \
                                        , 41204, 42238, 48135, 48832, 48966, 49078, 49108, 50120, 50162],
    'SNAP participation (1000)':[18183, 17194, 17318,19096, 25628, 35703, 26549, 19791, 26316, 21250, 40776, 23811, 42317, 44220, 45767, 46664 \
                                 , 40302, 46609, 47636, 28223, 44709, 33490],
                     })
xdata.head()

#CLEAN THE DATA
# data = data.replace(",", "", regex = True)
# data = data.replace(" ", "", regex = True)
data = data[0:50]
data

data = pd.DataFrame(data)
print(data.dtypes)

# data.plot(x='Food insecure individuals (1000)', 
#           y='SNAP participation (1000)', 
#           ax="r",
#           kind='scatter', 
#           figsize = (20,8),
#           grid = True, 
#           title = 'Food insecure & SNAP participation Scatter Graph')
# plt.scatter(x=data['Food insecure individuals (1000)'], 
#             y=data['SNAP participation (1000)'])

# FImean = data['Percentage FI'].mean()
# SNAPmean = data['Percentage SNAP'].mean()
FImean = 22
SNAPmean = 17

#ax = fig.add_subplot(111)
fig, ax = plt.subplots(figsize=(13, 8))

ax.scatter(data['Percentage FI'], 
        data['Percentage SNAP'])

#ax.annotate

ax.set_xlabel('Percentage of Food Insecurity', labelpad=20, size=15)
ax.set_ylabel('Percentage of SNAP', labelpad=20, size=15)
ax.set_title('Food Insecurity in relation to SNAP in each state, April 2020', pad=30, size=20)

ax.spines["bottom"].set_color("grey")
ax.spines["left"].set_color("grey")
ax.spines["top"].set_color("grey")
ax.spines["right"].set_color("grey")

plt.axhline(y=SNAPmean, c="blue", label="SNAP mean")
plt.axvline(x=FImean, c="red", label="FI mean")
plt.legend(("US SNAP mean", "US FI mean"), bbox_to_anchor=(1.3, 1), loc='upper right', fontsize=15)


ax.grid()


plt.show()

import plotly.express as px
import plotly.graph_objects as go

# FImean = 22
# SNAPmean = 17

fig = px.scatter(data, 
                 x="Percentage FI",
                 y="Percentage SNAP",
                 symbol="Political Party",
                 hover_name="State",
                 color='Ratio SNAP/FI',
                 width=1050, 
                 height=700)

fig.update_traces(mode='markers',
                  marker=dict(
                      size=12,
                      showscale=True,
                      colorbar=dict(title='Percentage of SNAPs in relation to Food Insecurity')
                  ))

fig.add_trace(go.Scatter(
    x=[22,22],
    y=[3,40],
    name="US Food Insecurity Average"))

fig.add_trace(go.Scatter(
    x=[7,40],
    y=[17, 17],
    name="US SNAP Average"))

fig.update_layout(title='Food Insecurity in relation to SNAP in each state, April 2020',
                  xaxis_title="Food Insecurity percentage per state",
                  yaxis_title="SNAP percentage per state",
                  paper_bgcolor=None,
                  legend=dict(yanchor="top",
                              y=0.99,
                              xanchor="left",
                              x=0.01))

fig.show()

"""**CONTEXTUAL ANALYSIS**

• Political problem

• Where SNAP participation needs to increase

"""
